name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      PIPELINE_TOKEN:
        required: true

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      # 1️⃣ Checkout pipeline-repot (där skripten finns)
      - name: Checkout pipeline repository
        uses: actions/checkout@v4

      # 2️⃣ Skriv ut vilket environment som körs
      - name: Print environment
        run: echo "Environment is ${{ inputs.environment }}"

      # 3️⃣ Kör rätt PowerShell-script baserat på environment
      - name: Run PowerShell script
        shell: pwsh
        run: |
          $scriptRoot = Join-Path $env:GITHUB_WORKSPACE "scripts"

          # Sätt execution policy för job session
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned -Force

          # Välj script baserat på environment
          if ("${{ inputs.environment }}" -eq "prod") {
              $scriptPath = Join-Path $scriptRoot "deploy-prod.ps1"
              Write-Host "Running prod script: $scriptPath"
          } elseif ("${{ inputs.environment }}" -eq "stage") {
              $scriptPath = Join-Path $scriptRoot "deploy-stage.ps1"
              Write-Host "Running stage script: $scriptPath"
          } else {
              $scriptPath = Join-Path $scriptRoot "deploy-test.ps1"
              Write-Host "Running test script: $scriptPath"
          }

          # Kontrollera att filen finns
          if (-Not (Test-Path $scriptPath)) {
              Write-Error "Script not found: $scriptPath"
              exit 1
          }

          # Avblockera och kör
          Unblock-File -Path $scriptPath
          & $scriptPath
