name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      PIPELINE_TOKEN:
        required: true

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment
        run: echo "Environment is ${{ inputs.environment }}"

      - name: Run PowerShell script
        run: |
          if ($env:environment -eq "prod") {
            Write-Host "Running prod script"
              scripts/deploy-prod.ps1
          } elseif ($env:environment -eq "stage") {
            Write-Host "Running stage script"
              scripts/deploy-stage.ps1
          } else {
            Write-Host "Running test script"
              scripts/deploy-test.ps1
          }
        shell: pwsh
        env:
          environment: ${{ inputs.environment }}
