- name: Run PowerShell script
  run: |
    $scriptRoot = Join-Path $env:GITHUB_WORKSPACE "scripts"

    # Sätt execution policy till RemoteSigned för job
    Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned -Force

    # Välj rätt script
    if ($env:environment -eq "prod") {
        $scriptPath = Join-Path $scriptRoot "deploy-prod.ps1"
        Write-Host "Running prod script: $scriptPath"
    } elseif ($env:environment -eq "stage") {
        $scriptPath = Join-Path $scriptRoot "deploy-stage.ps1"
        Write-Host "Running stage script: $scriptPath"
    } else {
        $scriptPath = Join-Path $scriptRoot "deploy-test.ps1"
        Write-Host "Running test script: $scriptPath"
    }

    # Unblock och kör
    Unblock-File -Path $scriptPath
    & $scriptPath
  shell: pwsh
  env:
    environment: ${{ inputs.environment }}
