name: Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      PIPELINE_TOKEN:
        required: true

jobs:
  run-powershell:
    runs-on: windows-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Print environment
      - name: Print environment
        run: echo "Environment is ${{ inputs.environment }}"

      # 3️⃣ Run the correct PowerShell script
      - name: Run PowerShell script
        run: |
          $scriptRoot = Join-Path $env:GITHUB_WORKSPACE "scripts"

          # Lista filer för felsökning
          Write-Host "Files in scripts folder:"
          Get-ChildItem -Path $scriptRoot

          # Sätt execution policy för job session
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned -Force

          # Välj script baserat på environment
          if ($env:environment -eq "prod") {
              $scriptPath = Join-Path $scriptRoot "deploy-prod.ps1"
              Write-Host "Running prod script: $scriptPath"
          } elseif ($env:environment -eq "stage") {
              $scriptPath = Join-Path $scriptRoot "deploy-stage.ps1"
              Write-Host "Running stage script: $scriptPath"
          } else {
              $scriptPath = Join-Path $scriptRoot "deploy-test.ps1"
              Write-Host "Running test script: $scriptPath"
          }

          # Kontrollera att filen finns
          if (Test-Path $scriptPath) {
              Unblock-File -Path $scriptPath
              & $scriptPath
          } else {
              Write-Error "Script not found: $scriptPath"
              exit 1
          }
        shell: pwsh
        env:
          environment: ${{ inputs.environment }}
